/**
 * worldviewPresets.js —— 10 骨架完整 profile 的前端镜像（P12.5）
 *
 * 设计取舍：后端 /api/worldview/schema 仅返回 preset 摘要（4 个高亮参数），
 * 但前端向导需要把选中骨架的完整 31 参数预填进 10 层向导。「backend untouched」
 * 铁律下不能加端点，故把 story_engine/worldview/presets.py 中 PRESETS 的
 * params 部分逐字镜像到这里——数据是静态字面量，与世界观子包版本对齐。
 *
 * 升级世界观子包时同步更新本文件（与后端 presets.py 保持逐字一致）。
 */

/* 10 骨架完整 params（与 presets.py PRESETS 同源，逐字一致） */
export const WV_PRESET_PARAMS = {
  hard_reality: {
    physics_deviation: 'none', metaphysics: 'materialist',
    time_structure: 'linear', space_structure: '3d_standard',
    causality: 'deterministic', consciousness_nature: 'emergent',
    information_laws: 'conserved', entropy_law: 'standard',
    cosmo_scope: 'universal', cosmo_mutability: 'immutable',
    divine_nature: 'absent', cosmo_cognition: 'known',
    origin_type: 'evolution', eschatology: 'heat_death',
    plane_structure: 'single', destiny_mechanism: 'none',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'standard',
    resource_paradigm: 'energy', magical_geography: 'none',
    environmental_hazards: 'natural_only', celestial_bodies: 'standard',
    infrastructure_level: 'developed',
    power_existence: 'nonexistent', power_source: 'internal',
    acquisition_method: 'innate', cost_structure: 'physical_fatigue',
    progression_model: 'none', system_transparency: 'hard',
    power_interaction: 'single', power_regulation: 'integrated',
  },
  xianxia_cultivation: {
    physics_deviation: 'major', metaphysics: 'dualist',
    time_structure: 'linear', space_structure: 'foldable',
    causality: 'intentional', consciousness_nature: 'soul_based',
    information_laws: 'conserved', entropy_law: 'reversed',
    cosmo_scope: 'universal', cosmo_mutability: 'mutable_force',
    divine_nature: 'ascended', cosmo_cognition: 'partially_known',
    origin_type: 'creation', eschatology: 'transcendence',
    plane_structure: 'nested', destiny_mechanism: 'threads',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'supernatural_atmosphere',
    resource_paradigm: 'energy', magical_geography: 'ley_lines',
    environmental_hazards: 'magical_storms', celestial_bodies: 'standard',
    infrastructure_level: 'magical',
    power_existence: 'common', power_source: 'external_environmental',
    acquisition_method: 'cultivation', cost_structure: 'consumption',
    progression_model: 'realm_breakthrough', system_transparency: 'semi_hard',
    power_interaction: 'hierarchical', power_regulation: 'self_regulated',
  },
  wuxia_jianghu: {
    physics_deviation: 'minor', metaphysics: 'materialist',
    time_structure: 'linear', space_structure: '3d_standard',
    causality: 'deterministic', consciousness_nature: 'emergent',
    information_laws: 'conserved', entropy_law: 'standard',
    cosmo_scope: 'regional', cosmo_mutability: 'immutable',
    divine_nature: 'absent', cosmo_cognition: 'known',
    origin_type: 'evolution', eschatology: 'unknown',
    plane_structure: 'single', destiny_mechanism: 'threads',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'standard',
    resource_paradigm: 'land', magical_geography: 'none',
    environmental_hazards: 'natural_only', celestial_bodies: 'standard',
    infrastructure_level: 'basic',
    power_existence: 'common', power_source: 'internal',
    acquisition_method: 'cultivation', cost_structure: 'physical_fatigue',
    progression_model: 'skill_tree', system_transparency: 'hard',
    power_interaction: 'single', power_regulation: 'self_regulated',
  },
  cthulhu_mythos: {
    physics_deviation: 'minor', metaphysics: 'custom',
    time_structure: 'linear', space_structure: 'non_euclidean',
    causality: 'chaotic', consciousness_nature: 'fundamental',
    information_laws: 'supernatural', entropy_law: 'standard',
    cosmo_scope: 'universal', cosmo_mutability: 'immutable',
    divine_nature: 'unknowable', cosmo_cognition: 'unknown',
    origin_type: 'mythic', eschatology: 'unknown',
    plane_structure: 'dual', destiny_mechanism: 'none',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'standard',
    resource_paradigm: 'information', magical_geography: 'cursed_lands',
    environmental_hazards: 'dimensional_incursions', celestial_bodies: 'standard',
    infrastructure_level: 'basic',
    power_existence: 'rare', power_source: 'knowledge_based',
    acquisition_method: 'study', cost_structure: 'backlash',
    progression_model: 'horizontal', system_transparency: 'mystery',
    power_interaction: 'single', power_regulation: 'unregulated',
  },
  cyberpunk: {
    physics_deviation: 'minor', metaphysics: 'materialist',
    time_structure: 'linear', space_structure: 'networked',
    causality: 'deterministic', consciousness_nature: 'substrate_independent',
    information_laws: 'destroyable', entropy_law: 'standard',
    cosmo_scope: 'regional', cosmo_mutability: 'immutable',
    divine_nature: 'absent', cosmo_cognition: 'partially_known',
    origin_type: 'evolution', eschatology: 'entropy_death',
    plane_structure: 'single', destiny_mechanism: 'threads',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'toxic',
    resource_paradigm: 'information', magical_geography: 'none',
    environmental_hazards: 'environmental_decay', celestial_bodies: 'standard',
    infrastructure_level: 'cyberpunk',
    power_existence: 'common', power_source: 'mixed',
    acquisition_method: 'mutation', cost_structure: 'addiction',
    progression_model: 'skill_tree', system_transparency: 'hard',
    power_interaction: 'stackable', power_regulation: 'government_regulated',
  },
  western_fantasy: {
    physics_deviation: 'minor', metaphysics: 'dualist',
    time_structure: 'linear', space_structure: 'multidimensional',
    causality: 'narrative', consciousness_nature: 'soul_based',
    information_laws: 'supernatural', entropy_law: 'standard',
    cosmo_scope: 'planar', cosmo_mutability: 'immutable',
    divine_nature: 'actor', cosmo_cognition: 'partially_known',
    origin_type: 'creation', eschatology: 'apocalypse',
    plane_structure: 'multiple', destiny_mechanism: 'prophecy',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'supernatural_atmosphere',
    resource_paradigm: 'artifact', magical_geography: 'ley_lines',
    environmental_hazards: 'monster_tides', celestial_bodies: 'standard',
    infrastructure_level: 'magical',
    power_existence: 'common', power_source: 'external_environmental',
    acquisition_method: 'study', cost_structure: 'consumption',
    progression_model: 'linear_levels', system_transparency: 'hard',
    power_interaction: 'stackable', power_regulation: 'self_regulated',
  },
  shanhai_zhiguai: {
    physics_deviation: 'minor', metaphysics: 'animist',
    time_structure: 'linear', space_structure: 'nested',
    causality: 'narrative', consciousness_nature: 'fundamental',
    information_laws: 'conserved', entropy_law: 'reversed',
    cosmo_scope: 'regional', cosmo_mutability: 'cyclical_mutability',
    divine_nature: 'actor', cosmo_cognition: 'partially_known',
    origin_type: 'mythic', eschatology: 'transcendence',
    plane_structure: 'nested', destiny_mechanism: 'prophecy',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'supernatural_atmosphere',
    resource_paradigm: 'land', magical_geography: 'ley_lines',
    environmental_hazards: 'monster_tides', celestial_bodies: 'astrological',
    infrastructure_level: 'basic',
    power_existence: 'rare', power_source: 'external_environmental',
    acquisition_method: 'cultivation', cost_structure: 'time_cost',
    progression_model: 'realm_breakthrough', system_transparency: 'medium',
    power_interaction: 'hierarchical', power_regulation: 'self_regulated',
  },
  infinite_flow: {
    physics_deviation: 'minor', metaphysics: 'materialist',
    time_structure: 'branching', space_structure: 'nested',
    causality: 'deterministic', consciousness_nature: 'substrate_independent',
    information_laws: 'creatable', entropy_law: 'standard',
    cosmo_scope: 'planar', cosmo_mutability: 'mutable_force',
    divine_nature: 'source', cosmo_cognition: 'unknown',
    origin_type: 'engineered', eschatology: 'engineered_end',
    plane_structure: 'multiple', destiny_mechanism: 'threads',
    terrain_paradigm: 'dimensional_maze', gravity_atmosphere: 'variable',
    resource_paradigm: 'artifact', magical_geography: 'dimensional_rifts',
    environmental_hazards: 'dimensional_incursions', celestial_bodies: 'standard',
    infrastructure_level: 'cyberpunk',
    power_existence: 'universal', power_source: 'systemic',
    acquisition_method: 'contract', cost_structure: 'consumption',
    progression_model: 'exponential', system_transparency: 'hard',
    power_interaction: 'stackable', power_regulation: 'weaponized',
  },
  post_apocalyptic: {
    physics_deviation: 'minor', metaphysics: 'materialist',
    time_structure: 'linear', space_structure: '3d_standard',
    causality: 'deterministic', consciousness_nature: 'emergent',
    information_laws: 'destroyable', entropy_law: 'accelerated',
    cosmo_scope: 'regional', cosmo_mutability: 'degrading',
    divine_nature: 'absent', cosmo_cognition: 'partially_known',
    origin_type: 'accident', eschatology: 'apocalypse',
    plane_structure: 'single', destiny_mechanism: 'none',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'toxic',
    resource_paradigm: 'life', magical_geography: 'cursed_lands',
    environmental_hazards: 'environmental_decay', celestial_bodies: 'standard',
    infrastructure_level: 'post_apocalyptic',
    power_existence: 'rare', power_source: 'internal',
    acquisition_method: 'mutation', cost_structure: 'physical_fatigue',
    progression_model: 'capped', system_transparency: 'hard',
    power_interaction: 'single', power_regulation: 'unregulated',
  },
  urban_supernatural: {
    physics_deviation: 'minor', metaphysics: 'dualist',
    time_structure: 'linear', space_structure: '3d_standard',
    causality: 'karmic', consciousness_nature: 'soul_based',
    information_laws: 'supernatural', entropy_law: 'standard',
    cosmo_scope: 'conditional', cosmo_mutability: 'immutable',
    divine_nature: 'unknowable', cosmo_cognition: 'unknown',
    origin_type: 'eternal', eschatology: 'unknown',
    plane_structure: 'dual', destiny_mechanism: 'karma',
    terrain_paradigm: 'earthlike', gravity_atmosphere: 'standard',
    resource_paradigm: 'artifact', magical_geography: 'cursed_lands',
    environmental_hazards: 'dimensional_incursions', celestial_bodies: 'event_significant',
    infrastructure_level: 'developed',
    power_existence: 'rare', power_source: 'bloodline',
    acquisition_method: 'innate', cost_structure: 'backlash',
    progression_model: 'horizontal', system_transparency: 'soft',
    power_interaction: 'single', power_regulation: 'suppressed',
  },
}

/**
 * 把扁平 preset params 转为分层结构 {L0:{...}, L1:{...}, ...}。
 * 反查表 layerOfParam 由调用方传入（来自 toWorldviewSchemaVM 的 paramMap）。
 */
export function presetToLayers(presetKey, schemaVM) {
  const flat = WV_PRESET_PARAMS[presetKey]
  if (!flat || !schemaVM) return {}
  const layers = {}
  for (const [paramKey, value] of Object.entries(flat)) {
    const layer = schemaVM.paramMap[paramKey]
    if (!layer) continue
    if (!layers[layer.id]) layers[layer.id] = {}
    layers[layer.id][paramKey] = value
  }
  return layers
}
