"""worldview layers — 世界观 10 层架构参数（批1：L0-L3 全量）

素材唯一来源：docs/世界观架构_参数全表.md（逐条录入，不臆造）。
连锁标记：``→`` 表示"会波及"，``↔`` 表示"互斥/必须一致"。

本批覆盖 L0 存在论 / L1 宇宙论 / L2 物理环境 / L3 力量体系，共 31 个参数。
每个参数含枚举值（value）+ 中文标签（label）+ 提示（hint）+ 连锁影响（chain）。
"""
from __future__ import annotations

# ----------------------------------------------------------------------------
# L0 · 存在论基础 (Ontological Foundation)
# ----------------------------------------------------------------------------
_L0 = {
    "id": "L0",
    "name": "存在论基础",
    "desc": "这个世界最底层的「真实」是什么？物理定律、形而上学、时间空间因果的根基。",
    "params": [
        {
            "key": "physics_deviation",
            "label": "物理偏离度",
            "options": [
                {"value": "none", "label": "完全遵循现实物理",
                 "hint": "所有超自然力量必须有局部豁免解释", "chain": ""},
                {"value": "minor", "label": "局部例外",
                 "hint": "基础物理不变，允许局部例外",
                 "chain": "→ L3 力量体系需解释为什么力大无穷但牛顿定律还在"},
                {"value": "major", "label": "核心物理定律被修改",
                 "hint": "灵气/暗能量/精神力成为第五基本力",
                 "chain": "→ L2 环境必须体现这种修改 → L3 力量体系建立在修改后的物理上 → L5 经济/科技围绕新物理运转"},
                {"value": "total", "label": "完全不同的物理体系",
                 "hint": "密实宇宙、二维世界、非欧时空",
                 "chain": "→ 所有层全部从零重建，需要独立的物理百科"},
            ],
        },
        {
            "key": "metaphysics",
            "label": "形而上学基底",
            "options": [
                {"value": "materialist", "label": "唯物",
                 "hint": "物质是唯一终极实在，意识是涌现产物",
                 "chain": "→ 无灵魂/无来世 → L1 无神或神=高级生物 → L6 宗教是纯粹社会现象"},
                {"value": "dualist", "label": "二元",
                 "hint": "物质世界与精神世界并行存在",
                 "chain": "→ 灵魂可独立存在 → 允许出窍/夺舍/转世 → L3 灵魂修炼 → L4 肉体态/灵魂态"},
                {"value": "idealist", "label": "唯心",
                 "hint": "意识是第一性的，物质是意识的投射",
                 "chain": "→ L0 因果=意图驱动（祈祷/诅咒有效）→ L3 力量=意志具现化"},
                {"value": "animist", "label": "万物有灵",
                 "hint": "一切存在都有某种程度的意识/灵性",
                 "chain": "→ L2 环境有意志 → L4 生命/非生命边界模糊 → L3 力量=与万物沟通"},
                {"value": "custom", "label": "自定义混合基底",
                 "hint": "需显式声明组合规则", "chain": ""},
            ],
        },
        {
            "key": "time_structure",
            "label": "时间结构",
            "options": [
                {"value": "linear", "label": "线性时间",
                 "hint": "不可逆", "chain": "→ 因果链单向 → 历史不可改变"},
                {"value": "cyclic", "label": "循环时间",
                 "hint": "轮回/纪元重置",
                 "chain": "→ L7 历史重复模式 → L1 末日/重生周期 → 前世记忆可存在"},
                {"value": "branching", "label": "分支时间",
                 "hint": "平行宇宙/多世界",
                 "chain": "→ 跨分支旅行可能 → 不同时间线可交叉"},
                {"value": "multiverse", "label": "多重时间轴并存",
                 "hint": "多条时间轴",
                 "chain": "→ L8 多真相共存 → 角色/读者无法确定哪个是真的"},
                {"value": "frozen", "label": "时间静止/可暂停",
                 "hint": "时间冻结区域内一切不变化",
                 "chain": "→ 力量可用于操纵时间"},
                {"value": "layered", "label": "多层时间",
                 "hint": "天上一天地上一年",
                 "chain": "→ 不同时间流速 → 跨层交互有时间差"},
            ],
        },
        {
            "key": "space_structure",
            "label": "空间结构",
            "options": [
                {"value": "3d_standard", "label": "三维标准空间",
                 "hint": "标准距离", "chain": "现实基底"},
                {"value": "multidimensional", "label": "多维空间",
                 "hint": "存在第四/第五维度",
                 "chain": "→ 高维/低维生物 → 空间折叠/穿越 → L3 空间系力量"},
                {"value": "foldable", "label": "可折叠空间",
                 "hint": "虫洞/传送阵",
                 "chain": "→ 瞬间移动 → L5 交通/战争/贸易模式改变"},
                {"value": "nested", "label": "嵌套空间",
                 "hint": "壶中天/洞天福地/梦中梦",
                 "chain": "→ 层级化世界 → 内外层规则可不同 → L2 地理复杂度剧增"},
                {"value": "non_euclidean", "label": "非欧几何空间",
                 "hint": "距离/方向概念不同",
                 "chain": "→ 方向感可被欺骗 → 克苏鲁式空间恐怖"},
                {"value": "networked", "label": "节点通道空间",
                 "hint": "迷宫/星门网络",
                 "chain": "→ 节点控制权=权力 → L5 贸易/军事围绕节点"},
            ],
        },
        {
            "key": "causality",
            "label": "因果律模式",
            "options": [
                {"value": "deterministic", "label": "严格因果律",
                 "hint": "相同条件=相同结果",
                 "chain": "→ 宿命论可能 → 心理史学可存在"},
                {"value": "probabilistic", "label": "概率因果",
                 "hint": "量子层面随机",
                 "chain": "→ L3 力量有随机成分 → L8 预言不精确"},
                {"value": "intentional", "label": "意志因果",
                 "hint": "意志/信念可直接影响物理现实",
                 "chain": "→ 祈祷/诅咒/信念有效 → L3 意念系力量 → L6 信仰=实际力量来源"},
                {"value": "narrative", "label": "叙事因果",
                 "hint": "故事逻辑取代物理因果（命运注定）",
                 "chain": "→ 预言可自我实现 → L7 历史=神话 → 主角光环可被世界规则合理化"},
                {"value": "karmic", "label": "因果报应",
                 "hint": "善有善报恶有恶报，宇宙有道德感",
                 "chain": "→ L5 法律可被因果取代 → L6 道德=实际生存策略"},
                {"value": "chaotic", "label": "无因果",
                 "hint": "因果不可追溯",
                 "chain": "→ L8 一切不可知 → 存在主义恐惧"},
            ],
        },
        {
            "key": "consciousness_nature",
            "label": "意识本质",
            "options": [
                {"value": "emergent", "label": "涌现产物",
                 "hint": "意识是大脑复杂度的涌现产物",
                 "chain": "→ 毁掉大脑=毁掉意识 → 无 AI 灵魂争议"},
                {"value": "fundamental", "label": "宇宙基本属性",
                 "hint": "泛心论",
                 "chain": "→ 万物有某种体验 → L4 AI/器物可觉醒 → L3 意念力量有物理基础"},
                {"value": "soul_based", "label": "灵魂载体",
                 "hint": "意识=灵魂，独立于肉体",
                 "chain": "→ 灵魂可转移/分裂/交易 → L3 神魂修炼 → L4 夺舍/转世"},
                {"value": "collective", "label": "集体意识",
                 "hint": "个体意识是整体的一部分",
                 "chain": "→ 蜂巢思维 → L5 社会结构=超个体 → L6 自我概念完全不同"},
                {"value": "substrate_independent", "label": "载体无关",
                 "hint": "意识不依赖特定载体（可上传/迁移）",
                 "chain": "→ L4 意识可存于机器/水晶/网络 → 数字永生 → 身份认同危机"},
            ],
        },
        {
            "key": "information_laws",
            "label": "信息法则",
            "options": [
                {"value": "conserved", "label": "信息守恒",
                 "hint": "不可创造不可毁灭",
                 "chain": "→ 完美的记忆可被恢复 → 历史可被还原"},
                {"value": "creatable", "label": "信息可凭空产生",
                 "hint": "信息可创造",
                 "chain": "→ 虚假/平行记忆可能 → L8 真相不可靠"},
                {"value": "destroyable", "label": "信息可永久抹除",
                 "hint": "信息可被毁灭",
                 "chain": "→ 记忆消除魔法 → L7 历史可被真正篡改 → L8 真相可永久丢失"},
                {"value": "supernatural", "label": "信息有超自然属性",
                 "hint": "真名/誓言有力量",
                 "chain": "→ L3 语言系魔法 → L6 命名=权力 → 真名=弱点"},
                {"value": "infectious", "label": "信息可感染/寄生",
                 "hint": "模因/克苏鲁知识",
                 "chain": "→ 知道不该知道的东西会发疯 → L8 禁忌知识真的危险"},
            ],
        },
        {
            "key": "entropy_law",
            "label": "熵/衰变法则",
            "options": [
                {"value": "standard", "label": "热力学第二定律",
                 "hint": "一切趋向无序",
                 "chain": "→ 万物会衰老死亡 → 能量有限"},
                {"value": "reversed", "label": "局部逆熵",
                 "hint": "灵气可逆熵→长生",
                 "chain": "→ L3 修炼=逆天改命 → L4 长生种 → L6 追求永生是合理目标"},
                {"value": "custom", "label": "自定义衰变规则",
                 "hint": "如只有活物衰变，器物不朽",
                 "chain": "需要明确声明"},
                {"value": "accelerated", "label": "加速衰变",
                 "hint": "末日废土/辐射世界",
                 "chain": "→ L2 资源枯竭 → L5 社会在崩溃边缘 → 生存=核心冲突"},
            ],
        },
    ],
}

# ----------------------------------------------------------------------------
# L1 · 宇宙论结构 (Cosmological Structure)
# ----------------------------------------------------------------------------
_L1 = {
    "id": "L1",
    "name": "宇宙论结构",
    "desc": "宇宙怎么组织的？有神吗？世界的起源和终结？多维度结构？",
    "params": [
        {
            "key": "cosmo_scope",
            "label": "宇宙影响范围",
            "options": [
                {"value": "universal", "label": "全宇宙",
                 "hint": "法则/力量影响整个宇宙（天道管一切）", "chain": ""},
                {"value": "regional", "label": "区域性",
                 "hint": "法则只在某些区域有效（某星球/大陆/结界内）", "chain": ""},
                {"value": "planar", "label": "位面性",
                 "hint": "每个位面/维度有自己的法则", "chain": ""},
                {"value": "personal", "label": "个体性",
                 "hint": "力量只影响个体或极小范围（个人信仰/血脉）", "chain": ""},
                {"value": "conditional", "label": "条件性",
                 "hint": "法则在特定条件下才生效（月圆/献祭/特定地点）", "chain": ""},
            ],
        },
        {
            "key": "cosmo_mutability",
            "label": "宇宙可变性",
            "options": [
                {"value": "immutable", "label": "永恒不变",
                 "hint": "规则永恒不变，神也不能改",
                 "chain": "→ 角色无法改变宇宙底层 → 力量上限锁死"},
                {"value": "mutable_force", "label": "力量可改规则",
                 "hint": "力量强大到一定程度可改规则",
                 "chain": "→ 顶级强者=神 → 力量体系无天花板 → 改天换地=终极目标"},
                {"value": "mutable_collective", "label": "集体意志可改规则",
                 "hint": "集体意志/信仰可改规则",
                 "chain": "→ L6 宗教=实际力量 → L5 政治=宇宙级博弈 → L8 真相由共识决定"},
                {"value": "cyclical_mutability", "label": "周期性重置",
                 "hint": "规则按周期自动重置（量劫）",
                 "chain": "→ L7 历史有循环模式 → 世界有大限"},
                {"value": "degrading", "label": "规则在退化",
                 "hint": "魔法在消亡/灵气在枯竭",
                 "chain": "→ L7 衰落叙事 → L2 资源递减 → 末法时代"},
            ],
        },
        {
            "key": "divine_nature",
            "label": "神性本质",
            "options": [
                {"value": "absent", "label": "无神",
                 "hint": "宇宙没有意志",
                 "chain": "→ L6 宗教=纯社会现象 → L8 宇宙真相=冷漠"},
                {"value": "actor", "label": "神是行动者",
                 "hint": "有意志、会干预、有人格",
                 "chain": "→ 神可直接出场 → L5 神权政治可能 → L3 神赐力量"},
                {"value": "source", "label": "神是法则源头",
                 "hint": "杀掉=法则消失",
                 "chain": "→ 杀神=改变世界 → L9 存在级冲突 → L8 真相=危险的"},
                {"value": "projection", "label": "神是信仰投射",
                 "hint": "没人信=神消失",
                 "chain": "→ L6 信仰=生存 → L5 传教=宇宙级工程 → 无神论=实际威胁"},
                {"value": "unknowable", "label": "不可知之神",
                 "hint": "神存在但不可知/不可理解",
                 "chain": "→ L8 克苏鲁式恐惧 → 理性无效 → 疯狂是合理反应"},
                {"value": "ascended", "label": "凡人封神",
                 "hint": "神是修炼/进化的终点（凡人可成神）",
                 "chain": "→ L3 无天花板 → L9 争夺神位 → L7 有凡人封神先例"},
            ],
        },
        {
            "key": "cosmo_cognition",
            "label": "宇宙真相认知度",
            "options": [
                {"value": "known", "label": "普遍知道",
                 "hint": "人们普遍知道宇宙真相",
                 "chain": "→ 无宗教争议 → 宇宙论是常识 → 降低认知冲突戏剧性"},
                {"value": "partially_known", "label": "部分人知道",
                 "hint": "部分人知道真相",
                 "chain": "→ L8 精英隐瞒真相 → L5 知识垄断=权力"},
                {"value": "unknown", "label": "几乎没人知道",
                 "hint": "几乎没人知道真相",
                 "chain": "→ L8 发现真相=巨大冲击 → L6 宗教=猜测 → 在黑暗中摸索"},
                {"value": "unknowable", "label": "不可完全认知",
                 "hint": "真相不可被完全认知",
                 "chain": "→ L8 永恒的恐惧/敬畏 → 理性探索有极限 → 存在主义危机"},
                {"value": "disputed", "label": "竞争性真相",
                 "hint": "多种宇宙论竞争，谁也不确定",
                 "chain": "→ L6 宗教战争 → L9 意识形态冲突 → L8 各有自己的真相"},
            ],
        },
        {
            "key": "origin_type",
            "label": "世界起源",
            "options": [
                {"value": "creation", "label": "创世行为",
                 "hint": "有意识的创世（神/盘古/工匠造物主）", "chain": ""},
                {"value": "evolution", "label": "自然演化",
                 "hint": "大爆炸→星系→生命", "chain": ""},
                {"value": "eternal", "label": "永恒存在",
                 "hint": "世界没有起源，永恒存在", "chain": ""},
                {"value": "cyclical_renewal", "label": "周期性毁灭与重生",
                 "hint": "周期性毁灭与重生", "chain": ""},
                {"value": "accident", "label": "偶然事件",
                 "hint": "实验事故/维度碰撞", "chain": ""},
                {"value": "engineered", "label": "被设计/制造",
                 "hint": "虚拟世界/缸中之脑/文明遗产", "chain": ""},
                {"value": "mythic", "label": "神话叙事起源",
                 "hint": "不太逻辑，有诗意/象征性", "chain": ""},
            ],
        },
        {
            "key": "eschatology",
            "label": "世界终结",
            "options": [
                {"value": "heat_death", "label": "热寂",
                 "hint": "缓慢归于虚无", "chain": "→ 生存焦虑但时间充裕"},
                {"value": "apocalypse", "label": "末日",
                 "hint": "突然的大灾变",
                 "chain": "→ L9 紧迫的存在威胁 → L2 环境灾难"},
                {"value": "eternal_cycle", "label": "无终结循环",
                 "hint": "无终结，只有循环",
                 "chain": "→ 终结=新开始 → L7 历史重复"},
                {"value": "transcendence", "label": "超越",
                 "hint": "世界会进化到更高形态",
                 "chain": "→ L3 进化=终极目标 → L9 存在级追求"},
                {"value": "entropy_death", "label": "熵死",
                 "hint": "魔法/能量缓慢耗尽",
                 "chain": "→ 末法时代 → L2 灵气枯竭 → L7 衰落叙事"},
                {"value": "engineered_end", "label": "被外部终结",
                 "hint": "模拟器关闭/造物主回收",
                 "chain": "→ L8 真相极其恐怖 → L9 与造物主对抗"},
                {"value": "unknown", "label": "未知",
                 "hint": "不知道世界会怎么结束",
                 "chain": "→ L8 悬念 → 角色在不确定中行动"},
            ],
        },
        {
            "key": "plane_structure",
            "label": "位面/维度结构",
            "options": [
                {"value": "single", "label": "单一物理世界",
                 "hint": "只有一个物理世界", "chain": "简化"},
                {"value": "dual", "label": "物理+精神双世界",
                 "hint": "阴阳两界/现世+幽冥",
                 "chain": "→ 跨界可能 → L3 通灵系力量 → L4 死后的存在"},
                {"value": "multiple", "label": "多个平行位面",
                 "hint": "元素位面/神域/魔界",
                 "chain": "→ L2 跨界旅行 → L5 多世界政治 → L4 跨位面物种"},
                {"value": "nested", "label": "位面嵌套",
                 "hint": "天界→人界→冥界，层级分明",
                 "chain": "→ 层级=力量等级 → L3 飞升/堕入机制"},
                {"value": "infinite", "label": "无限多位面",
                 "hint": "无限多个位面/世界",
                 "chain": "→ 多元宇宙 → L9 无限可能 → L8 没有唯一真相"},
                {"value": "collapsed", "label": "位面融合/破碎",
                 "hint": "曾经多位面，现在融合/破碎",
                 "chain": "→ L7 大事件=位面融合 → L2 混乱环境 → L4 跨物种混居"},
            ],
        },
        {
            "key": "destiny_mechanism",
            "label": "命运机制",
            "options": [
                {"value": "none", "label": "无命运",
                 "hint": "完全自由意志", "chain": ""},
                {"value": "threads", "label": "命运之线",
                 "hint": "每个人都有预设路径，但可偏离", "chain": ""},
                {"value": "prophecy", "label": "预言",
                 "hint": "未来可被预言但不一定精确", "chain": ""},
                {"value": "karma", "label": "业力",
                 "hint": "过去的行为决定未来的遭遇", "chain": ""},
                {"value": "predestination", "label": "宿命",
                 "hint": "一切已注定，无法改变", "chain": ""},
                {"value": "competing_fates", "label": "竞争命运",
                 "hint": "多种命运竞争，看谁实现", "chain": ""},
                {"value": "self_fulfilling", "label": "自我实现",
                 "hint": "命运=自我实现的预言（知道了就注定发生）", "chain": ""},
            ],
        },
    ],
}

# ----------------------------------------------------------------------------
# L2 · 物理环境 (Physical Environment)
# ----------------------------------------------------------------------------
_L2 = {
    "id": "L2",
    "name": "物理环境",
    "desc": "世界的地理、资源、生态、气候、天体、基础设施。",
    "params": [
        {
            "key": "terrain_paradigm",
            "label": "地形范式",
            "options": [
                {"value": "earthlike", "label": "类地球地形",
                 "hint": "大陆/海洋/山脉/沙漠", "chain": ""},
                {"value": "floating", "label": "漂浮地块",
                 "hint": "浮空城市/天空岛", "chain": ""},
                {"value": "underground", "label": "地下世界",
                 "hint": "洞穴文明", "chain": ""},
                {"value": "underwater", "label": "水下文明", "hint": "水下文明", "chain": ""},
                {"value": "dimensional_maze", "label": "维度迷宫",
                 "hint": "空间不连续，由通道连接", "chain": ""},
                {"value": "ringworld", "label": "环形世界",
                 "hint": "戴森球/巨型结构", "chain": ""},
                {"value": "custom", "label": "自定义地形",
                 "hint": "完全自定义地形", "chain": ""},
                {"value": "mixed", "label": "混合地形",
                 "hint": "地表+地下+浮空等", "chain": ""},
            ],
        },
        {
            "key": "gravity_atmosphere",
            "label": "重力与大气",
            "options": [
                {"value": "standard", "label": "标准",
                 "hint": "1G 重力，氮氧大气", "chain": "现实基底"},
                {"value": "extreme_gravity", "label": "极端重力",
                 "hint": "超重力或微重力",
                 "chain": "→ 人体形态改变 → L4 物种适应 → 战斗方式不同"},
                {"value": "supernatural_atmosphere", "label": "超自然大气",
                 "hint": "大气含超自然元素（灵气/魔力/辐射）",
                 "chain": "→ 呼吸=吸收力量 → L3 力量来源=环境"},
                {"value": "toxic", "label": "有毒大气",
                 "hint": "大气有毒，需防护",
                 "chain": "→ 生存=日常挑战 → L5 社会围绕防护运转"},
                {"value": "variable", "label": "可变重力/大气",
                 "hint": "因地而异",
                 "chain": "→ L2 危险区域 → L5 迁徙/贸易受限"},
            ],
        },
        {
            # 复合参数：源 P2.3 由 key_resource / scarcity_level / distribution /
            # substitutability 四子项构成。此处以最关键的 key_resource 为主枚举，
            # 其余子项在选项 hint 中标注。see docs: 行 230-246。
            "key": "resource_paradigm",
            "label": "资源范式（最稀缺资源）",
            "options": [
                {"value": "none", "label": "无特殊稀缺资源",
                 "hint": "无；稀缺度 abundant/adequate/scarce/critical/exhausted", "chain": ""},
                {"value": "energy", "label": "能源",
                 "hint": "石油/灵石/晶核/香料", "chain": "稀缺资源=冲突引擎"},
                {"value": "life", "label": "生命资源",
                 "hint": "水/食物/药材/基因", "chain": "稀缺资源=冲突引擎"},
                {"value": "information", "label": "信息/知识",
                 "hint": "信息/知识/秘密", "chain": "稀缺资源=冲突引擎"},
                {"value": "land", "label": "领土",
                 "hint": "领土/灵脉/圣地", "chain": "稀缺资源=冲突引擎"},
                {"value": "people", "label": "人本身",
                 "hint": "奴隶/血脉/灵魂/信徒", "chain": "稀缺资源=冲突引擎"},
                {"value": "artifact", "label": "远古遗物",
                 "hint": "远古遗物/神器", "chain": "稀缺资源=冲突引擎"},
            ],
        },
        {
            "key": "magical_geography",
            "label": "超自然地理",
            "options": [
                {"value": "none", "label": "无超自然地理",
                 "hint": "现实地理", "chain": ""},
                {"value": "ley_lines", "label": "地脉/灵脉网络",
                 "hint": "地脉/灵脉",
                 "chain": "→ 节点=价值地段 → 门派据点选址 → L5 领土争夺"},
                {"value": "mana_zones", "label": "魔力浓度区域",
                 "hint": "高/低浓度区",
                 "chain": "→ 高浓度=修炼圣地 → 低浓度=荒原 → 迁徙动力"},
                {"value": "cursed_lands", "label": "诅咒/污染区域",
                 "hint": "禁区",
                 "chain": "→ 冒险/探索目标 → L2 环境危险"},
                {"value": "sacred_sites", "label": "神圣/圣遗地",
                 "hint": "朝圣",
                 "chain": "→ L6 宗教 → L5 控制=合法性"},
                {"value": "dimensional_rifts", "label": "维度裂缝/传送门",
                 "hint": "连接不同世界",
                 "chain": "→ L1 多位面 → 意外入侵可能"},
                {"value": "shifting", "label": "地理会变化",
                 "hint": "移动的大陆/季节性出现",
                 "chain": "→ 地图不稳定 → 探索永无止境 → L7 制图学=力量"},
            ],
        },
        {
            "key": "environmental_hazards",
            "label": "环境威胁",
            "options": [
                {"value": "natural_only", "label": "仅自然灾害",
                 "hint": "地震/洪灾/瘟疫", "chain": ""},
                {"value": "magical_storms", "label": "超自然风暴",
                 "hint": "灵气风暴/魔力潮汐/虚空侵蚀", "chain": ""},
                {"value": "monster_tides", "label": "怪物潮",
                 "hint": "兽潮周期性爆发", "chain": ""},
                {"value": "dimensional_incursions", "label": "维度入侵",
                 "hint": "异界生物/虚空裂缝", "chain": ""},
                {"value": "environmental_decay", "label": "环境衰退",
                 "hint": "沙漠化/灵气枯竭/辐射扩散", "chain": ""},
                {"value": "celestial_events", "label": "天体事件",
                 "hint": "日食触发变异/彗星带来灾难", "chain": ""},
                {"value": "none_significant", "label": "无重大威胁",
                 "hint": "无重大环境威胁", "chain": ""},
            ],
        },
        {
            # 复合参数：源 P2.6 由 sun_count / moon_count / visible_stars /
            # celestial_events_significance 四子项构成。此处以最关键的配置形态
            # 为主枚举。see docs: 行 272-279。
            "key": "celestial_bodies",
            "label": "天体配置",
            "options": [
                {"value": "standard", "label": "标准天体",
                 "hint": "单日单月，星座无超自然意义", "chain": ""},
                {"value": "multi_sun", "label": "多日",
                 "hint": "几个太阳？（影响光照/气候/神话）", "chain": ""},
                {"value": "multi_moon", "label": "多月",
                 "hint": "几个月亮？（影响潮汐/魔法周期/狼人变形）", "chain": ""},
                {"value": "astrological", "label": "占星有效",
                 "hint": "星座有意义（占星术是否有效→L0 因果律）", "chain": ""},
                {"value": "event_significant", "label": "天体事件有效",
                 "hint": "天体事件有超自然效果（日食=力量增强）", "chain": ""},
            ],
        },
        {
            "key": "infrastructure_level",
            "label": "基础设施水平",
            "options": [
                {"value": "primitive", "label": "无基础设施",
                 "hint": "部落/荒野",
                 "chain": "→ 旅行困难 → L5 社会分散"},
                {"value": "basic", "label": "基础道路/驿站",
                 "hint": "道路/驿站/城墙",
                 "chain": "→ 区域贸易可能"},
                {"value": "developed", "label": "完善交通网",
                 "hint": "交通网/通讯系统/城市",
                 "chain": "→ 大规模贸易/战争"},
                {"value": "magical", "label": "魔法/修炼设施",
                 "hint": "传送阵/飞剑快递/灵兽交通",
                 "chain": "→ L3 力量体系日常化 → L5 社会运转依赖力量"},
                {"value": "steampunk", "label": "蒸汽/机械设施",
                 "hint": "工业化世界",
                 "chain": "→ L5 阶级分化"},
                {"value": "cyberpunk", "label": "赛博基础设施",
                 "hint": "数字化",
                 "chain": "→ 信息=资源 → L8 数据控制=权力"},
                {"value": "post_apocalyptic", "label": "废墟（曾发达）",
                 "hint": "曾经发达，现在废墟",
                 "chain": "→ L7 文明衰退 → 发掘旧世界遗产=核心活动"},
            ],
        },
    ],
}

# ----------------------------------------------------------------------------
# L3 · 力量体系 (Power Systems)
# ----------------------------------------------------------------------------
_L3 = {
    "id": "L3",
    "name": "力量体系",
    "desc": "有什么超出常人的力量？怎么获取？代价？进阶？多体系如何互动？",
    "params": [
        {
            "key": "power_existence",
            "label": "力量存在性",
            "options": [
                {"value": "universal", "label": "全民皆有",
                 "hint": "所有人都有力量（或都有潜力）", "chain": ""},
                {"value": "common", "label": "相当部分人有",
                 "hint": "约 1/10", "chain": ""},
                {"value": "rare", "label": "少数人有",
                 "hint": "约 1/1000", "chain": ""},
                {"value": "unique", "label": "极少数人有",
                 "hint": "几十个", "chain": ""},
                {"value": "nonexistent", "label": "无超自然力量",
                 "hint": "纯现实世界", "chain": ""},
                {"value": "dormant", "label": "沉睡/待激活",
                 "hint": "力量曾经存在但现在沉睡/需要特定条件激活", "chain": ""},
            ],
        },
        {
            "key": "power_source",
            "label": "力量来源",
            "options": [
                {"value": "internal", "label": "身体自生",
                 "hint": "内功/血脉/基因", "chain": "典型：武侠/超级英雄"},
                {"value": "external_material", "label": "消耗外部物质",
                 "hint": "吞金属/吃灵药/用法器", "chain": "典型：迷雾之子/修真丹药"},
                {"value": "external_environmental", "label": "从环境汲取",
                 "hint": "灵气/魔力场/太阳能量", "chain": "典型：修真/法力恢复"},
                {"value": "granted", "label": "被赋予",
                 "hint": "神赐/契约/传承", "chain": "典型：神眷者/圣骑士"},
                {"value": "systemic", "label": "系统面板",
                 "hint": "LitRPG/数值化", "chain": "典型：无限流/游戏世界"},
                {"value": "knowledge_based", "label": "知识/语言/符文",
                 "hint": "念咒/画阵/真名", "chain": "典型：哈利波特/魔法阵"},
                {"value": "bloodline", "label": "血脉天赋",
                 "hint": "天生就有某种能力", "chain": "典型：异世界/变异种"},
                {"value": "mixed", "label": "多来源混合",
                 "hint": "多来源混合", "chain": "大多数复杂世界"},
            ],
        },
        {
            "key": "acquisition_method",
            "label": "获取方式",
            "options": [
                {"value": "cultivation", "label": "修炼积累",
                 "hint": "打坐/练功/历练", "chain": "进度感：读者跟着角色一起成长"},
                {"value": "innate", "label": "先天天赋",
                 "hint": "出生决定", "chain": "命运感：天赋高低=命运安排"},
                {"value": "study", "label": "知识学习",
                 "hint": "魔法学院/秘籍研读", "chain": "成长感：勤奋可弥补天赋"},
                {"value": "contract", "label": "契约/交易",
                 "hint": "与神/恶魔/系统签约", "chain": "代价感：获取即负债"},
                {"value": "mutation", "label": "变异/意外",
                 "hint": "被咬/辐射/实验", "chain": "不可控：随机/不可复制"},
                {"value": "bestowal", "label": "被赐予",
                 "hint": "神选中/传承/灌顶", "chain": "使命感：被选中的人"},
                {"value": "theft", "label": "夺取",
                 "hint": "吸功/吞噬/剥夺", "chain": "黑暗向：力量来自掠夺"},
                {"value": "awakening", "label": "觉醒",
                 "hint": "体内沉睡力量被激活", "chain": "悬念：什么时候觉醒？觉醒什么？"},
            ],
        },
        {
            # Sanderson 第二定律：限制比能力更有趣。
            "key": "cost_structure",
            "label": "代价结构",
            "options": [
                {"value": "consumption", "label": "消耗资源",
                 "hint": "耗蓝/耗灵石/耗气血", "chain": "资源管理→策略性使用"},
                {"value": "physical_fatigue", "label": "体力消耗",
                 "hint": "用多了累/伤", "chain": "节奏控制→不能无限使用"},
                {"value": "backlash", "label": "反噬",
                 "hint": "走火入魔/精神污染/器官损伤", "chain": "风险决策：值不值得冒险？"},
                {"value": "sacrifice", "label": "牺牲",
                 "hint": "献祭记忆/寿命/器官/亲人", "chain": "情感代价→道德困境"},
                {"value": "corruption", "label": "堕落",
                 "hint": "使用越多越堕落/越不人", "chain": "道德弧光→用不用力量本身就是冲突"},
                {"value": "addiction", "label": "成瘾",
                 "hint": "力量本身让人上瘾", "chain": "角色缺陷→戒断/复发"},
                {"value": "time_cost", "label": "时间代价",
                 "hint": "修炼需大量时间/施法需长准备", "chain": "紧迫感→时间不够"},
                {"value": "social_cost", "label": "社会代价",
                 "hint": "暴露力量=被追杀/被崇拜", "chain": "隐藏身份→秘密生活"},
                {"value": "none", "label": "无代价",
                 "hint": "无代价", "chain": "⚠️ 危险——容易变爽文/无张力"},
                {"value": "multiple", "label": "多种代价叠加",
                 "hint": "多种代价叠加", "chain": "最有深度"},
            ],
        },
        {
            "key": "progression_model",
            "label": "进阶模型",
            "options": [
                {"value": "linear_levels", "label": "线性等级",
                 "hint": "1级→2级→3级", "chain": "对标：RPG/LitRPG"},
                {"value": "realm_breakthrough", "label": "境界突破",
                 "hint": "筑基→金丹→元婴", "chain": "对标：修真"},
                {"value": "skill_tree", "label": "技能树",
                 "hint": "可选择不同分支", "chain": "对标：游戏化"},
                {"value": "exponential", "label": "指数增长",
                 "hint": "每个层次差距巨大", "chain": "对标：修真（高一境界碾压）"},
                {"value": "boundless", "label": "无上限",
                 "hint": "永远可以更强", "chain": "对标：武功（天下第一没有天花板）"},
                {"value": "capped", "label": "有天花板",
                 "hint": "最高等级明确", "chain": "对标：超能力世界"},
                {"value": "horizontal", "label": "横向扩展",
                 "hint": "不是变强而是学更多技能", "chain": "对标：魔法学院"},
                {"value": "transformation", "label": "质变",
                 "hint": "不是数值增长而是形态进化", "chain": "对标：变身/进化系"},
                {"value": "none", "label": "无进阶",
                 "hint": "力量固定不变", "chain": "对标：吸血鬼（转化后能力固定）"},
            ],
        },
        {
            # Sanderson 第一定律精确化
            "key": "system_transparency",
            "label": "规则透明度",
            "options": [
                {"value": "hard", "label": "硬魔法",
                 "hint": "规则完全透明，读者可推演",
                 "chain": "参与感强，可预测；✅ 可以解决冲突"},
                {"value": "semi_hard", "label": "半硬魔法",
                 "hint": "基本规则透明，有少量未知",
                 "chain": "有惊喜空间；✅ 基本可以解决冲突"},
                {"value": "medium", "label": "中等透明",
                 "hint": "部分透明，部分模糊",
                 "chain": "好奇心驱动；⚠️ 仅限模糊部分不可解冲突"},
                {"value": "soft", "label": "软魔法",
                 "hint": "规则模糊，充满神秘感",
                 "chain": "敬畏和惊奇；❌ 不可以解决冲突"},
                {"value": "mystery", "label": "完全不可知",
                 "hint": "连角色都不理解",
                 "chain": "恐惧和绝望；❌ 绝不可以解决冲突"},
            ],
        },
        {
            "key": "power_interaction",
            "label": "多体系互动",
            "options": [
                {"value": "single", "label": "单一体系",
                 "hint": "只有一种力量体系", "chain": "简化"},
                {"value": "exclusive", "label": "互斥",
                 "hint": "多体系互斥（有魔法就不能修武）",
                 "chain": "→ L9 体系间对立 → 身份选择=人生选择"},
                {"value": "stackable", "label": "可叠加",
                 "hint": "魔法+武功+科技",
                 "chain": "→ 最强=全栈 → L9 争夺稀缺资源"},
                {"value": "transformative", "label": "可转化",
                 "hint": "一种力量可转化为另一种",
                 "chain": "→ 转化效率=策略核心"},
                {"value": "conflicting", "label": "互相冲突/抵消",
                 "hint": "魔法克科技",
                 "chain": "→ 相克关系 → L9 石头剪刀布博弈"},
                {"value": "hierarchical", "label": "有高低之分",
                 "hint": "修真>武功>凡人",
                 "chain": "→ L5 阶层固化 → 弱者无翻身可能"},
                {"value": "synergistic", "label": "互相增幅",
                 "hint": "魔法+科技>各自之和",
                 "chain": "→ 融合=终极追求 → L9 抢夺融合者"},
            ],
        },
        {
            "key": "power_regulation",
            "label": "力量管理",
            "options": [
                {"value": "unregulated", "label": "无管理",
                 "hint": "谁强谁说了算",
                 "chain": "→ 弱肉强食 → L5 混乱"},
                {"value": "self_regulated", "label": "行业自律",
                 "hint": "宗门规矩/法师行会",
                 "chain": "→ 非正式秩序 → 违规者被同行惩罚"},
                {"value": "government_regulated", "label": "政府管控",
                 "hint": "注册/执照/监控",
                 "chain": "→ L5 力量者 vs 政府 → L9 自由vs安全"},
                {"value": "suppressed", "label": "被压制/禁止",
                 "hint": "力量被压制",
                 "chain": "→ 地下力量者 → L9 反抗体制"},
                {"value": "weaponized", "label": "军事化",
                 "hint": "力量被军事化",
                 "chain": "→ 力量者=兵器 → L5 军国主义"},
                {"value": "integrated", "label": "社会正常部分",
                 "hint": "力量是社会正常组成部分",
                 "chain": "→ 无特殊管理 → 力量=日常"},
            ],
        },
    ],
}

LAYERS = [_L0, _L1, _L2, _L3]

ALL_PARAMS = {p["key"]: p for layer in LAYERS for p in layer["params"]}

LAYER_BY_ID = {layer["id"]: layer for layer in LAYERS}


def param_values(key: str) -> list[str]:
    """返回某参数的全部合法枚举值；未知键返回空列表。"""
    p = ALL_PARAMS.get(key)
    return [o["value"] for o in p["options"]] if p else []


def option_label(key: str, value: str) -> str:
    """返回某参数某值的中文标签；未知返回值本身。"""
    p = ALL_PARAMS.get(key)
    if not p:
        return value
    for o in p["options"]:
        if o["value"] == value:
            return o["label"]
    return value
