"""worldview presets — 十骨架经典世界观预设（P12.4 / P12.7）

10 个经典叙事骨架的完整 L0-L9 世界观档案。每个 preset 填满全部 71 个参数，
所有取值均为 :data:`layers.ALL_PARAMS` 中登记的合法枚举值，且通过
:func:`predicates.evaluate` 无违例。

骨架灵感来源：task brief 表格（非逐字，是合理推演），参数组合忠实于
``docs/世界观架构_参数全表.md`` 的连锁约束。

字段说明::

    {
      "key":   骨架 slug（API 引用名），
      "name":  中文名，
      "vibe":  一句话气质（前端展示用），
      "params": {<param_key>: <enum_value>, ...}  # 71 个参数全填
    }
"""
from __future__ import annotations

PRESETS: list[dict] = [
    # ---------------------------------------------------------------- 1
    {
        "key": "hard_reality",
        "name": "现实本格",
        "vibe": "严格遵循现实物理的纯粹现实世界，悬疑/本格推理的底座。",
        "params": {
            # L0
            "physics_deviation": "none",
            "metaphysics": "materialist",
            "time_structure": "linear",
            "space_structure": "3d_standard",
            "causality": "deterministic",
            "consciousness_nature": "emergent",
            "information_laws": "conserved",
            "entropy_law": "standard",
            # L1
            "cosmo_scope": "universal",
            "cosmo_mutability": "immutable",
            "divine_nature": "absent",
            "cosmo_cognition": "known",
            "origin_type": "evolution",
            "eschatology": "heat_death",
            "plane_structure": "single",
            "destiny_mechanism": "none",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "standard",
            "resource_paradigm": "energy",
            "magical_geography": "none",
            "environmental_hazards": "natural_only",
            "celestial_bodies": "standard",
            "infrastructure_level": "developed",
            # L3
            "power_existence": "nonexistent",
            "power_source": "internal",
            "acquisition_method": "innate",
            "cost_structure": "physical_fatigue",
            "progression_model": "none",
            "system_transparency": "hard",
            "power_interaction": "single",
            "power_regulation": "integrated",
            # L4 物种生态
            "species_diversity": "many",
            "species_origin": "natural",
            "species_hierarchy": "dominant",
            "mortality_model": "mortal",
            "transformation_type": "none",
            "biological_basis": "genetic",
            "cross_species_rules": "impossible",
            # L5 社会结构
            "political_system": "republic",
            "economic_system": "capitalist",
            "stratification_basis": "wealth",
            "knowledge_distribution": "open",
            "legal_system": "rule_of_law",
            "military_organization": "standing_army",
            "power_society_relation": "separated",
            # L6 文化与信仰
            "language_paradigm": "diverse",
            "religion_type": "polytheist",
            "core_values": "survival",
            "taboo_system": "moral",
            "death_customs": "final",
            "education_system": "systematic",
            "gender_family_structure": "egalitarian",
            "aesthetic_ideal": "classical",
            # L7 历史与时间线
            "timeline_depth": "deep",
            "history_accuracy": "accurate",
            "civilization_cycle": "ascending",
            "lost_civilizations": "none",
            "artifact_significance": "functional",
            "historical_relevance": "influential",
            # L8 认知与真相
            "truth_structure": "single",
            "information_asymmetry": "individual",
            "hidden_truths": "none",
            "forbidden_knowledge": "political",
            "knowledge_reliability": "certain",
            "discovery_potential": "possible",
            "memory_system": "reliable",
            # L9 存在级冲突
            "conflict_types": "resource",
            "conflict_intensity": "medium",
            "conflict_scale": "multi_scale",
            "conflict_resolution": "law",
            "tension_source": "power_gap",
        },
    },
    # ---------------------------------------------------------------- 2
    {
        "key": "xianxia_cultivation",
        "name": "修真问道",
        "vibe": "灵气为第五基本力，逆天改命、飞升长生的修仙宇宙。",
        "params": {
            # L0
            "physics_deviation": "major",
            "metaphysics": "dualist",
            "time_structure": "linear",
            "space_structure": "foldable",
            "causality": "intentional",
            "consciousness_nature": "soul_based",
            "information_laws": "conserved",
            "entropy_law": "reversed",
            # L1
            "cosmo_scope": "universal",
            "cosmo_mutability": "mutable_force",
            "divine_nature": "ascended",
            "cosmo_cognition": "partially_known",
            "origin_type": "creation",
            "eschatology": "transcendence",
            "plane_structure": "nested",
            "destiny_mechanism": "threads",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "supernatural_atmosphere",
            "resource_paradigm": "energy",
            "magical_geography": "ley_lines",
            "environmental_hazards": "magical_storms",
            "celestial_bodies": "standard",
            "infrastructure_level": "magical",
            # L3
            "power_existence": "common",
            "power_source": "external_environmental",
            "acquisition_method": "cultivation",
            "cost_structure": "consumption",
            "progression_model": "realm_breakthrough",
            "system_transparency": "semi_hard",
            "power_interaction": "hierarchical",
            "power_regulation": "self_regulated",
            # L4 物种生态
            "species_diversity": "many",
            "species_origin": "mixed",
            "species_hierarchy": "hierarchical",
            "mortality_model": "conditional_immortal",
            "transformation_type": "upgradeable",
            "biological_basis": "mixed",
            "cross_species_rules": "common",
            # L5 社会结构
            "political_system": "sect_based",
            "economic_system": "magical_resource",
            "stratification_basis": "birth",
            "knowledge_distribution": "restricted",
            "legal_system": "customary",
            "military_organization": "magical_order",
            "power_society_relation": "stratifying",
            # L6 文化与信仰
            "language_paradigm": "diverse",
            "religion_type": "polytheist",
            "core_values": "power",
            "taboo_system": "magical",
            "death_customs": "deferred",
            "education_system": "apprenticeship",
            "gender_family_structure": "segregated",
            "aesthetic_ideal": "sublime",
            # L7 历史与时间线
            "timeline_depth": "mythic",
            "history_accuracy": "mythologized",
            "civilization_cycle": "ascending",
            "lost_civilizations": "precursor",
            "artifact_significance": "powerful",
            "historical_relevance": "haunting",
            # L8 认知与真相
            "truth_structure": "layered",
            "information_asymmetry": "elite",
            "hidden_truths": "power_source_hidden",
            "forbidden_knowledge": "corrupting",
            "knowledge_reliability": "biased",
            "discovery_potential": "transformative",
            "memory_system": "inherited",
            # L9 存在级冲突
            "conflict_types": "power_hierarchy",
            "conflict_intensity": "extreme",
            "conflict_scale": "multi_scale",
            "conflict_resolution": "violence",
            "tension_source": "power_gap",
        },
    },
    # ---------------------------------------------------------------- 3
    {
        "key": "wuxia_jianghu",
        "name": "武侠江湖",
        "vibe": "内力为尊、恩怨分明，没有天花板的武学江湖。",
        "params": {
            # L0
            "physics_deviation": "minor",
            "metaphysics": "materialist",
            "time_structure": "linear",
            "space_structure": "3d_standard",
            "causality": "deterministic",
            "consciousness_nature": "emergent",
            "information_laws": "conserved",
            "entropy_law": "standard",
            # L1
            "cosmo_scope": "regional",
            "cosmo_mutability": "immutable",
            "divine_nature": "absent",
            "cosmo_cognition": "known",
            "origin_type": "evolution",
            "eschatology": "unknown",
            "plane_structure": "single",
            "destiny_mechanism": "threads",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "standard",
            "resource_paradigm": "land",
            "magical_geography": "none",
            "environmental_hazards": "natural_only",
            "celestial_bodies": "standard",
            "infrastructure_level": "basic",
            # L3
            "power_existence": "common",
            "power_source": "internal",
            "acquisition_method": "cultivation",
            "cost_structure": "physical_fatigue",
            "progression_model": "skill_tree",
            "system_transparency": "hard",
            "power_interaction": "single",
            "power_regulation": "self_regulated",
            # L4 物种生态
            "species_diversity": "single",
            "species_origin": "natural",
            "species_hierarchy": "egalitarian",
            "mortality_model": "mortal",
            "transformation_type": "upgradeable",
            "biological_basis": "genetic",
            "cross_species_rules": "impossible",
            # L5 社会结构
            "political_system": "sect_based",
            "economic_system": "feudal",
            "stratification_basis": "power",
            "knowledge_distribution": "restricted",
            "legal_system": "customary",
            "military_organization": "knightly_order",
            "power_society_relation": "integrated",
            # L6 文化与信仰
            "language_paradigm": "unified",
            "religion_type": "atheist",
            "core_values": "honor",
            "taboo_system": "moral",
            "death_customs": "final",
            "education_system": "apprenticeship",
            "gender_family_structure": "segregated",
            "aesthetic_ideal": "classical",
            # L7 历史与时间线
            "timeline_depth": "medium",
            "history_accuracy": "mythologized",
            "civilization_cycle": "peak",
            "lost_civilizations": "none",
            "artifact_significance": "identity",
            "historical_relevance": "haunting",
            # L8 认知与真相
            "truth_structure": "single",
            "information_asymmetry": "individual",
            "hidden_truths": "none",
            "forbidden_knowledge": "political",
            "knowledge_reliability": "biased",
            "discovery_potential": "possible",
            "memory_system": "fallible",
            # L9 存在级冲突
            "conflict_types": "personal_vendetta",
            "conflict_intensity": "high",
            "conflict_scale": "factional",
            "conflict_resolution": "violence",
            "tension_source": "moral",
        },
    },
    # ---------------------------------------------------------------- 4
    {
        "key": "cthulhu_mythos",
        "name": "克苏鲁神话",
        "vibe": "宇宙级冷漠与不可名状的禁忌知识，理性在恐惧前崩溃。",
        "params": {
            # L0
            "physics_deviation": "minor",
            "metaphysics": "custom",
            "time_structure": "linear",
            "space_structure": "non_euclidean",
            "causality": "chaotic",
            "consciousness_nature": "fundamental",
            "information_laws": "supernatural",
            "entropy_law": "standard",
            # L1
            "cosmo_scope": "universal",
            "cosmo_mutability": "immutable",
            "divine_nature": "unknowable",
            "cosmo_cognition": "unknown",
            "origin_type": "mythic",
            "eschatology": "unknown",
            "plane_structure": "dual",
            "destiny_mechanism": "none",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "standard",
            "resource_paradigm": "information",
            "magical_geography": "cursed_lands",
            "environmental_hazards": "dimensional_incursions",
            "celestial_bodies": "standard",
            "infrastructure_level": "basic",
            # L3
            "power_existence": "rare",
            "power_source": "knowledge_based",
            "acquisition_method": "study",
            "cost_structure": "backlash",
            "progression_model": "horizontal",
            "system_transparency": "mystery",
            "power_interaction": "single",
            "power_regulation": "unregulated",
            # L4 物种生态
            "species_diversity": "infinite",
            "species_origin": "dimensional",
            "species_hierarchy": "fluid",
            "mortality_model": "undead",
            "transformation_type": "forced",
            "biological_basis": "environmental",
            "cross_species_rules": "taboo",
            # L5 社会结构
            "political_system": "tribal",
            "economic_system": "barter",
            "stratification_basis": "knowledge",
            "knowledge_distribution": "lost",
            "legal_system": "customary",
            "military_organization": "none",
            "power_society_relation": "suppressed",
            # L6 文化与信仰
            "language_paradigm": "lost_language",
            "religion_type": "cult",
            "core_values": "survival",
            "taboo_system": "existential",
            "death_customs": "contagious",
            "education_system": "secretive",
            "gender_family_structure": "segregated",
            "aesthetic_ideal": "dark",
            # L7 历史与时间线
            "timeline_depth": "eternal",
            "history_accuracy": "contradictory",
            "civilization_cycle": "fallen",
            "lost_civilizations": "mythical",
            "artifact_significance": "dangerous",
            "historical_relevance": "haunting",
            # L8 认知与真相
            "truth_structure": "contradictory",
            "information_asymmetry": "individual",
            "hidden_truths": "origin_hidden",
            "forbidden_knowledge": "corrupting",
            "knowledge_reliability": "unknowable",
            "discovery_potential": "dangerous",
            "memory_system": "cursed",
            # L9 存在级冲突
            "conflict_types": "cosmic",
            "conflict_intensity": "total",
            "conflict_scale": "cosmic",
            "conflict_resolution": "impossible",
            "tension_source": "mystery",
        },
    },
    # ---------------------------------------------------------------- 5
    {
        "key": "cyberpunk",
        "name": "赛博朋克",
        "vibe": "高科技低生活，巨头垄断与数据洪流中的霓虹废墟。",
        "params": {
            # L0
            "physics_deviation": "minor",
            "metaphysics": "materialist",
            "time_structure": "linear",
            "space_structure": "networked",
            "causality": "deterministic",
            "consciousness_nature": "substrate_independent",
            "information_laws": "destroyable",
            "entropy_law": "standard",
            # L1
            "cosmo_scope": "regional",
            "cosmo_mutability": "immutable",
            "divine_nature": "absent",
            "cosmo_cognition": "partially_known",
            "origin_type": "evolution",
            "eschatology": "entropy_death",
            "plane_structure": "single",
            "destiny_mechanism": "threads",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "toxic",
            "resource_paradigm": "information",
            "magical_geography": "none",
            "environmental_hazards": "environmental_decay",
            "celestial_bodies": "standard",
            "infrastructure_level": "cyberpunk",
            # L3
            "power_existence": "common",
            "power_source": "mixed",
            "acquisition_method": "mutation",
            "cost_structure": "addiction",
            "progression_model": "skill_tree",
            "system_transparency": "hard",
            "power_interaction": "stackable",
            "power_regulation": "government_regulated",
            # L4 物种生态
            "species_diversity": "few",
            "species_origin": "engineered",
            "species_hierarchy": "segregated",
            "mortality_model": "mortal",
            "transformation_type": "upgradeable",
            "biological_basis": "genetic",
            "cross_species_rules": "rare",
            # L5 社会结构
            "political_system": "corporatocracy",
            "economic_system": "capitalist",
            "stratification_basis": "wealth",
            "knowledge_distribution": "monopolized",
            "legal_system": "contractual",
            "military_organization": "corporate_army",
            "power_society_relation": "regulated",
            # L6 文化与信仰
            "language_paradigm": "diverse",
            "religion_type": "cult",
            "core_values": "power",
            "taboo_system": "social",
            "death_customs": "negotiable",
            "education_system": "self_taught",
            "gender_family_structure": "fluid",
            "aesthetic_ideal": "technological",
            # L7 历史与时间线
            "timeline_depth": "shallow",
            "history_accuracy": "revised",
            "civilization_cycle": "declining",
            "lost_civilizations": "recently_fallen",
            "artifact_significance": "functional",
            "historical_relevance": "background",
            # L8 认知与真相
            "truth_structure": "manufactured",
            "information_asymmetry": "class_divided",
            "hidden_truths": "nature_hidden",
            "forbidden_knowledge": "destabilizing",
            "knowledge_reliability": "manipulated",
            "discovery_potential": "dangerous",
            "memory_system": "tradeable",
            # L9 存在级冲突
            "conflict_types": "class",
            "conflict_intensity": "high",
            "conflict_scale": "national",
            "conflict_resolution": "violence",
            "tension_source": "power_gap",
        },
    },
    # ---------------------------------------------------------------- 6
    {
        "key": "western_fantasy",
        "name": "西幻史诗",
        "vibe": "众神创世、魔力涌动，魔法学院与英雄宿命交织的史诗大陆。",
        "params": {
            # L0
            "physics_deviation": "minor",
            "metaphysics": "dualist",
            "time_structure": "linear",
            "space_structure": "multidimensional",
            "causality": "narrative",
            "consciousness_nature": "soul_based",
            "information_laws": "supernatural",
            "entropy_law": "standard",
            # L1
            "cosmo_scope": "planar",
            "cosmo_mutability": "immutable",
            "divine_nature": "actor",
            "cosmo_cognition": "partially_known",
            "origin_type": "creation",
            "eschatology": "apocalypse",
            "plane_structure": "multiple",
            "destiny_mechanism": "prophecy",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "supernatural_atmosphere",
            "resource_paradigm": "artifact",
            "magical_geography": "ley_lines",
            "environmental_hazards": "monster_tides",
            "celestial_bodies": "standard",
            "infrastructure_level": "magical",
            # L3
            "power_existence": "common",
            "power_source": "external_environmental",
            "acquisition_method": "study",
            "cost_structure": "consumption",
            "progression_model": "linear_levels",
            "system_transparency": "hard",
            "power_interaction": "stackable",
            "power_regulation": "self_regulated",
            # L4 物种生态
            "species_diversity": "many",
            "species_origin": "created",
            "species_hierarchy": "hierarchical",
            "mortality_model": "mortal",
            "transformation_type": "upgradeable",
            "biological_basis": "mixed",
            "cross_species_rules": "common",
            # L5 社会结构
            "political_system": "monarchy",
            "economic_system": "feudal",
            "stratification_basis": "birth",
            "knowledge_distribution": "restricted",
            "legal_system": "divine_law",
            "military_organization": "knightly_order",
            "power_society_relation": "integrated",
            # L6 文化与信仰
            "language_paradigm": "ancient_power",
            "religion_type": "polytheist",
            "core_values": "honor",
            "taboo_system": "religious",
            "death_customs": "transition",
            "education_system": "academy",
            "gender_family_structure": "patriarchal",
            "aesthetic_ideal": "sublime",
            # L7 历史与时间线
            "timeline_depth": "deep",
            "history_accuracy": "mythologized",
            "civilization_cycle": "peak",
            "lost_civilizations": "precursor",
            "artifact_significance": "powerful",
            "historical_relevance": "driving",
            # L8 认知与真相
            "truth_structure": "layered",
            "information_asymmetry": "elite",
            "hidden_truths": "power_source_hidden",
            "forbidden_knowledge": "locked",
            "knowledge_reliability": "biased",
            "discovery_potential": "possible",
            "memory_system": "inherited",
            # L9 存在级冲突
            "conflict_types": "ideological",
            "conflict_intensity": "extreme",
            "conflict_scale": "civilizational",
            "conflict_resolution": "violence",
            "tension_source": "moral",
        },
    },
    # ---------------------------------------------------------------- 7
    {
        "key": "shanhai_zhiguai",
        "name": "山海志怪",
        "vibe": "万物有灵、山神水府，壶中洞天与飞升得道的华夏志怪世界。",
        "params": {
            # L0
            "physics_deviation": "minor",
            "metaphysics": "animist",
            "time_structure": "linear",
            "space_structure": "nested",
            "causality": "narrative",
            "consciousness_nature": "fundamental",
            "information_laws": "conserved",
            "entropy_law": "reversed",
            # L1
            "cosmo_scope": "regional",
            "cosmo_mutability": "cyclical_mutability",
            "divine_nature": "actor",
            "cosmo_cognition": "partially_known",
            "origin_type": "mythic",
            "eschatology": "transcendence",
            "plane_structure": "nested",
            "destiny_mechanism": "prophecy",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "supernatural_atmosphere",
            "resource_paradigm": "land",
            "magical_geography": "ley_lines",
            "environmental_hazards": "monster_tides",
            "celestial_bodies": "astrological",
            "infrastructure_level": "basic",
            # L3
            "power_existence": "rare",
            "power_source": "external_environmental",
            "acquisition_method": "cultivation",
            "cost_structure": "time_cost",
            "progression_model": "realm_breakthrough",
            "system_transparency": "medium",
            "power_interaction": "hierarchical",
            "power_regulation": "self_regulated",
            # L4 物种生态
            "species_diversity": "mythic",
            "species_origin": "natural",
            "species_hierarchy": "hierarchical",
            "mortality_model": "conditional_immortal",
            "transformation_type": "mutable",
            "biological_basis": "spiritual",
            "cross_species_rules": "common",
            # L5 社会结构
            "political_system": "theocracy",
            "economic_system": "magical_resource",
            "stratification_basis": "birth",
            "knowledge_distribution": "restricted",
            "legal_system": "divine_law",
            "military_organization": "magical_order",
            "power_society_relation": "revere",
            # L6 文化与信仰
            "language_paradigm": "diverse",
            "religion_type": "animist",
            "core_values": "harmony",
            "taboo_system": "magical",
            "death_customs": "deferred",
            "education_system": "secretive",
            "gender_family_structure": "egalitarian",
            "aesthetic_ideal": "natural",
            # L7 历史与时间线
            "timeline_depth": "mythic",
            "history_accuracy": "mythologized",
            "civilization_cycle": "peak",
            "lost_civilizations": "mythical",
            "artifact_significance": "identity",
            "historical_relevance": "haunting",
            # L8 认知与真相
            "truth_structure": "fragmented",
            "information_asymmetry": "elite",
            "hidden_truths": "entity_hidden",
            "forbidden_knowledge": "religious",
            "knowledge_reliability": "biased",
            "discovery_potential": "transformative",
            "memory_system": "inherited",
            # L9 存在级冲突
            "conflict_types": "cosmic",
            "conflict_intensity": "extreme",
            "conflict_scale": "multi_scale",
            "conflict_resolution": "ritual",
            "tension_source": "identity",
        },
    },
    # ---------------------------------------------------------------- 8
    {
        "key": "infinite_flow",
        "name": "无限流",
        "vibe": "主神空间驱动的副本轮回，系统面板与兑换点数堆叠出无限可能。",
        "params": {
            # L0
            "physics_deviation": "minor",
            "metaphysics": "materialist",
            "time_structure": "branching",
            "space_structure": "nested",
            "causality": "deterministic",
            "consciousness_nature": "substrate_independent",
            "information_laws": "creatable",
            "entropy_law": "standard",
            # L1
            "cosmo_scope": "planar",
            "cosmo_mutability": "mutable_force",
            "divine_nature": "source",
            "cosmo_cognition": "unknown",
            "origin_type": "engineered",
            "eschatology": "engineered_end",
            "plane_structure": "multiple",
            "destiny_mechanism": "threads",
            # L2
            "terrain_paradigm": "dimensional_maze",
            "gravity_atmosphere": "variable",
            "resource_paradigm": "artifact",
            "magical_geography": "dimensional_rifts",
            "environmental_hazards": "dimensional_incursions",
            "celestial_bodies": "standard",
            "infrastructure_level": "cyberpunk",
            # L3
            "power_existence": "universal",
            "power_source": "systemic",
            "acquisition_method": "contract",
            "cost_structure": "consumption",
            "progression_model": "exponential",
            "system_transparency": "hard",
            "power_interaction": "stackable",
            "power_regulation": "weaponized",
            # L4 物种生态
            "species_diversity": "few",
            "species_origin": "engineered",
            "species_hierarchy": "segregated",
            "mortality_model": "conditional_immortal",
            "transformation_type": "upgradeable",
            "biological_basis": "genetic",
            "cross_species_rules": "common",
            # L5 社会结构
            "political_system": "technocracy",
            "economic_system": "post_scarcity",
            "stratification_basis": "power",
            "knowledge_distribution": "monopolized",
            "legal_system": "contractual",
            "military_organization": "none",
            "power_society_relation": "regulated",
            # L6 文化与信仰
            "language_paradigm": "unified",
            "religion_type": "verified",
            "core_values": "survival",
            "taboo_system": "existential",
            "death_customs": "negotiable",
            "education_system": "systematic",
            "gender_family_structure": "fluid",
            "aesthetic_ideal": "minimalist",
            # L7 历史与时间线
            "timeline_depth": "shallow",
            "history_accuracy": "revised",
            "civilization_cycle": "reset",
            "lost_civilizations": "one",
            "artifact_significance": "functional",
            "historical_relevance": "background",
            # L8 认知与真相
            "truth_structure": "recursive",
            "information_asymmetry": "individual",
            "hidden_truths": "cost_hidden",
            "forbidden_knowledge": "destabilizing",
            "knowledge_reliability": "unreliable",
            "discovery_potential": "inevitable",
            "memory_system": "manipulable",
            # L9 存在级冲突
            "conflict_types": "existential",
            "conflict_intensity": "extreme",
            "conflict_scale": "multi_scale",
            "conflict_resolution": "violence",
            "tension_source": "countdown",
        },
    },
    # ---------------------------------------------------------------- 9
    {
        "key": "post_apocalyptic",
        "name": "末日废土",
        "vibe": "大灾变后的辐射荒原，净水即生命、变异即生存的崩溃文明。",
        "params": {
            # L0
            "physics_deviation": "minor",
            "metaphysics": "materialist",
            "time_structure": "linear",
            "space_structure": "3d_standard",
            "causality": "deterministic",
            "consciousness_nature": "emergent",
            "information_laws": "destroyable",
            "entropy_law": "accelerated",
            # L1
            "cosmo_scope": "regional",
            "cosmo_mutability": "degrading",
            "divine_nature": "absent",
            "cosmo_cognition": "partially_known",
            "origin_type": "accident",
            "eschatology": "apocalypse",
            "plane_structure": "single",
            "destiny_mechanism": "none",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "toxic",
            "resource_paradigm": "life",
            "magical_geography": "cursed_lands",
            "environmental_hazards": "environmental_decay",
            "celestial_bodies": "standard",
            "infrastructure_level": "post_apocalyptic",
            # L3
            "power_existence": "rare",
            "power_source": "internal",
            "acquisition_method": "mutation",
            "cost_structure": "physical_fatigue",
            "progression_model": "capped",
            "system_transparency": "hard",
            "power_interaction": "single",
            "power_regulation": "unregulated",
            # L4 物种生态
            "species_diversity": "few",
            "species_origin": "mutated",
            "species_hierarchy": "segregated",
            "mortality_model": "mortal",
            "transformation_type": "degradable",
            "biological_basis": "environmental",
            "cross_species_rules": "rare",
            # L5 社会结构
            "political_system": "anarchy",
            "economic_system": "barter",
            "stratification_basis": "power",
            "knowledge_distribution": "lost",
            "legal_system": "none",
            "military_organization": "militia",
            "power_society_relation": "separated",
            # L6 文化与信仰
            "language_paradigm": "diverse",
            "religion_type": "cult",
            "core_values": "survival",
            "taboo_system": "moral",
            "death_customs": "final",
            "education_system": "self_taught",
            "gender_family_structure": "segregated",
            "aesthetic_ideal": "brutal",
            # L7 历史与时间线
            "timeline_depth": "shallow",
            "history_accuracy": "lost",
            "civilization_cycle": "fallen",
            "lost_civilizations": "recently_fallen",
            "artifact_significance": "identity",
            "historical_relevance": "haunting",
            # L8 认知与真相
            "truth_structure": "fragmented",
            "information_asymmetry": "geographic",
            "hidden_truths": "history_hidden",
            "forbidden_knowledge": "dangerous",
            "knowledge_reliability": "unreliable",
            "discovery_potential": "difficult",
            "memory_system": "fallible",
            # L9 存在级冲突
            "conflict_types": "resource",
            "conflict_intensity": "extreme",
            "conflict_scale": "national",
            "conflict_resolution": "violence",
            "tension_source": "survival",
        },
    },
    # ---------------------------------------------------------------- 10
    {
        "key": "urban_supernatural",
        "name": "都市灵异",
        "vibe": "霓虹灯下的灵界重叠，阴阳眼与凶宅秘闻的现代怪谈。",
        "params": {
            # L0
            "physics_deviation": "minor",
            "metaphysics": "dualist",
            "time_structure": "linear",
            "space_structure": "3d_standard",
            "causality": "karmic",
            "consciousness_nature": "soul_based",
            "information_laws": "supernatural",
            "entropy_law": "standard",
            # L1
            "cosmo_scope": "conditional",
            "cosmo_mutability": "immutable",
            "divine_nature": "unknowable",
            "cosmo_cognition": "unknown",
            "origin_type": "eternal",
            "eschatology": "unknown",
            "plane_structure": "dual",
            "destiny_mechanism": "karma",
            # L2
            "terrain_paradigm": "earthlike",
            "gravity_atmosphere": "standard",
            "resource_paradigm": "artifact",
            "magical_geography": "cursed_lands",
            "environmental_hazards": "dimensional_incursions",
            "celestial_bodies": "event_significant",
            "infrastructure_level": "developed",
            # L3
            "power_existence": "rare",
            "power_source": "bloodline",
            "acquisition_method": "innate",
            "cost_structure": "backlash",
            "progression_model": "horizontal",
            "system_transparency": "soft",
            "power_interaction": "single",
            "power_regulation": "suppressed",
            # L4 物种生态
            "species_diversity": "few",
            "species_origin": "dimensional",
            "species_hierarchy": "fluid",
            "mortality_model": "undead",
            "transformation_type": "forced",
            "biological_basis": "spiritual",
            "cross_species_rules": "taboo",
            # L5 社会结构
            "political_system": "republic",
            "economic_system": "capitalist",
            "stratification_basis": "knowledge",
            "knowledge_distribution": "open",
            "legal_system": "rule_of_law",
            "military_organization": "none",
            "power_society_relation": "suppressed",
            # L6 文化与信仰
            "language_paradigm": "diverse",
            "religion_type": "ancestor",
            "core_values": "faith",
            "taboo_system": "religious",
            "death_customs": "transition",
            "education_system": "systematic",
            "gender_family_structure": "family_nuclear",
            "aesthetic_ideal": "dark",
            # L7 历史与时间线
            "timeline_depth": "medium",
            "history_accuracy": "censored",
            "civilization_cycle": "static",
            "lost_civilizations": "none",
            "artifact_significance": "identity",
            "historical_relevance": "haunting",
            # L8 认知与真相
            "truth_structure": "layered",
            "information_asymmetry": "individual",
            "hidden_truths": "entity_hidden",
            "forbidden_knowledge": "religious",
            "knowledge_reliability": "unreliable",
            "discovery_potential": "dangerous",
            "memory_system": "manipulable",
            # L9 存在级冲突
            "conflict_types": "epistemological",
            "conflict_intensity": "high",
            "conflict_scale": "personal",
            "conflict_resolution": "diplomacy",
            "tension_source": "mystery",
        },
    },
]

PRESET_BY_KEY: dict[str, dict] = {p["key"]: p for p in PRESETS}


def preset_summaries() -> list[dict]:
    """返回前端友好的 preset 摘要列表（key/name/vibe + 关键参数摘要）。"""
    out: list[dict] = []
    for p in PRESETS:
        params = p["params"]
        # 摘要：挑 4 个最具辨识度的参数（中文标签化由前端或 option_label 处理，
        # 此处返回 key=value 原始串，保持端点轻量）
        highlight_keys = ("physics_deviation", "metaphysics",
                          "power_source", "power_existence")
        summary = "；".join(f"{k}={params[k]}" for k in highlight_keys)
        out.append({
            "key": p["key"],
            "name": p["name"],
            "vibe": p["vibe"],
            "summary": summary,
        })
    return out
